# Lab | Data Cleaning and Formatting

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

# Challenge 1: Data Cleaning and Formatting

## Exercise 1: Cleaning Column Names

To ensure consistency and ease of use, standardize the column names of the dataframe. Start by taking a first look at the dataframe and identifying any column names that need to be modified. Use appropriate naming conventions and make sure that column names are descriptive and informative.

*Hint*:
- *Column names should be in lower case*
- *White spaces in column names should be replaced by `_`*
- *`st` could be replaced for `state`*

In [86]:
# Your code here
import pandas as pd

url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"
insurance_df = pd.read_csv(url)

In [3]:
insurance_df.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [4]:
insurance_df.columns

Index(['Customer', 'ST', 'GENDER', 'Education', 'Customer Lifetime Value',
       'Income', 'Monthly Premium Auto', 'Number of Open Complaints',
       'Policy Type', 'Vehicle Class', 'Total Claim Amount'],
      dtype='str')

In [87]:
insurance_df.rename(columns={"ST": "state", "GENDER" : "gender", "Customer" : "id_customer", "Education" : "education"}, inplace=True)
print(insurance_df.columns)

Index(['id_customer', 'state', 'gender', 'education',
       'Customer Lifetime Value', 'Income', 'Monthly Premium Auto',
       'Number of Open Complaints', 'Policy Type', 'Vehicle Class',
       'Total Claim Amount'],
      dtype='str')

In [88]:
insurance_df.rename(columns={"Customer Lifetime Value" : "c_lifetime_value", "Monthly Premium Auto" : "monthly_premium_auto","Number of Open Complaints" : "number_open_complaints", "Policy Type" : "policy_type", "Vehicle Class" : "vehicle_class", 
"Total Claim Amount" : "total_claim_amount"}, inplace=True)
print(insurance_df.columns)

Index(['id_customer', 'state', 'gender', 'education', 'c_lifetime_value',
       'Income', 'monthly_premium_auto', 'number_open_complaints',
       'policy_type', 'vehicle_class', 'total_claim_amount'],
      dtype='str')

## Exercise 2: Cleaning invalid Values

The dataset contains columns with inconsistent and incorrect values that could affect the accuracy of our analysis. Therefore, we need to clean these columns to ensure that they only contain valid data.

Note that this exercise will focus only on cleaning inconsistent values and will not involve handling null values (NaN or None).

*Hint*:
- *Gender column contains various inconsistent values such as "F", "M", "Femal", "Male", "female", which need to be standardized, for example, to "M" and "F".*
- *State abbreviations be can replaced with its full name, for example "AZ": "Arizona", "Cali": "California", "WA": "Washington"*
- *In education, "Bachelors" could be replaced by "Bachelor"*
- *In Customer Lifetime Value, delete the `%` character*
- *In vehicle class, "Sports Car", "Luxury SUV" and "Luxury Car" could be replaced by "Luxury"*

In [8]:
# Your code here
#Checking distinct values - Inspecting
insurance_df["gender"].unique()
insurance_df["gender"].value_counts()

gender
F         457
M         413
Male       39
female     28
Femal      17
Name: count, dtype: int64

In [11]:
insurance_df["gender"] = insurance_df["gender"].replace({
    "Male" : "M",
    "Female" : "F",
    "Femal" : "F",
})

In [15]:
insurance_df["gender"].unique()
insurance_df["gender"].value_counts()
#Standardised gender values

gender
F         474
M         452
female     28
Name: count, dtype: int64

In [17]:
#Checking values for state
insurance_df["state"].unique()
insurance_df["state"].value_counts()

state
Oregon        320
California    211
Arizona       186
Cali          120
Nevada         98
Washington     81
WA             30
AZ             25
Name: count, dtype: int64

In [18]:
#Standardised values for state
insurance_df["state"] = insurance_df["state"].replace({
    "Cali" : "California",
    "WA" : "Washington",
    "AZ": "Arizona",
})

insurance_df["state"].unique()
insurance_df["state"].value_counts()

state
California    331
Oregon        320
Arizona       211
Washington    111
Nevada         98
Name: count, dtype: int64

In [19]:
#Checking values for Education
insurance_df["education"].unique()
insurance_df["education"].value_counts()

education
Bachelor                324
College                 313
High School or Below    296
Master                   94
Doctor                   37
Bachelors                 7
Name: count, dtype: int64

In [21]:
#Standardises values for education
insurance_df["education"] = insurance_df["education"].replace({
    "Bachelors" : "Bachelor"
})

insurance_df["education"].unique()
insurance_df["education"].value_counts()

education
Bachelor                331
College                 313
High School or Below    296
Master                   94
Doctor                   37
Name: count, dtype: int64

In [22]:
#Checking values for Customer Life Time Value
insurance_df["c_lifetime_value"].unique()

<ArrowStringArray>
[          nan,  '697953.59%', '1288743.17%',  '764586.18%',  '536307.65%',
  '825629.78%',  '538089.86%',  '721610.03%', '2412750.40%',  '738817.81%',
 ...
  '943891.56%', '1050677.17%',  '421391.86%',  '477368.64%',  '544142.01%',
  '284226.69%',  '305955.03%', '2031499.76%',  '323912.47%',  '899704.02%']
Length: 1028, dtype: str

In [32]:
#Formatting values for Customer Life Time Value
insurance_df["c_lifetime_value"] = insurance_df["c_lifetime_value"].str.replace(r"[^a-zA-Z0-9.]", "", regex=True)
insurance_df["c_lifetime_value"].unique()
insurance_df["c_lifetime_value"].value_counts()

c_lifetime_value
445811.34     4
251459.20     4
2412750.40    3
684615.03     3
578018.22     3
             ..
284226.69     1
305955.03     1
2031499.76    1
323912.47     1
899704.02     1
Name: count, Length: 1027, dtype: int64

In [40]:
#Checking values for vehicle clas
insurance_df["vehicle_class"].unique()
insurance_df["vehicle_class"].value_counts()

vehicle_class
Four-Door Car    576
Two-Door Car     205
SUV              199
Sports Car        57
Luxury SUV        20
Luxury Car        14
Name: count, dtype: int64

In [44]:
#Standarsided values for vehicle class
insurance_df["vehicle_class"] = insurance_df["vehicle_class"].replace({
    "Sports Car" : "Luxury",
    "Luxury SUV" : "Luxury",
    "Luxury Car" : "Luxury",
})

insurance_df["vehicle_class"].unique()
insurance_df["vehicle_class"].value_counts()

vehicle_class
Four-Door Car    576
Two-Door Car     205
SUV              199
Luxury            91
Name: count, dtype: int64

## Exercise 3: Formatting data types

The data types of many columns in the dataset appear to be incorrect. This could impact the accuracy of our analysis. To ensure accurate analysis, we need to correct the data types of these columns. Please update the data types of the columns as appropriate.

It is important to note that this exercise does not involve handling null values (NaN or None).

*Hint*:
- *Customer lifetime value should be numeric*
- *Number of open complaints has an incorrect format. Look at the different values it takes with `unique()` and take the middle value. As an example, 1/5/00 should be 5. Number of open complaints is a string - remember you can use `split()` to deal with it and take the number you need. Finally, since it should be numeric, cast the column to be in its proper type.*

In [76]:
#Checking the type of the column c_lifetime_value
insurance_df["c_lifetime_value"].dtype

In [49]:
#Changing c_lifetime_value to numeric
insurance_df["c_lifetime_value"] = pd.to_numeric(insurance_df["c_lifetime_value"], errors="coerce")
insurance_df["c_lifetime_value"].dtype

dtype('float64')

In [81]:
insurance_df["number_open_complaints"].unique()

<ArrowStringArray>
['1/0/00', '1/2/00', '1/1/00', '1/3/00', '1/5/00', '1/4/00', nan]
Length: 7, dtype: str

In [51]:
insurance_df["number_open_complaints"].dtype

In [60]:
insurance_df["number_open_complaints"].isna().sum()

np.int64(2937)

In [61]:
#Checking values in open_complaints
len(insurance_df["number_open_complaints"])

In [62]:
insurance_df["number_open_complaints"].unique()

<ArrowStringArray>
['1/0/00', '1/2/00', '1/1/00', '1/3/00', '1/5/00', '1/4/00', nan]
Length: 7, dtype: str

In [63]:
insurance_df["number_open_complaints"].value_counts()

number_open_complaints
1/0/00    830
1/1/00    138
1/2/00     50
1/3/00     34
1/4/00     13
1/5/00      6
Name: count, dtype: int64

In [89]:
#Splitting the string and grabbing the middle value(1)
insurance_df["number_open_complaints"] = insurance_df["number_open_complaints"].str.split("/").str[1]

In [90]:
insurance_df["number_open_complaints"].unique()

array(['0', '2', '1', '3', '5', '4', nan], dtype=object)

In [91]:
#Casting to numeric
insurance_df["number_open_complaints"] = pd.to_numeric(insurance_df["number_open_complaints"], errors="coerce")

In [92]:
insurance_df["number_open_complaints"].unique()

array([ 0.,  2.,  1.,  3.,  5.,  4., nan])

In [93]:
insurance_df["number_open_complaints"].dtype

dtype('float64')

In [94]:
insurance_df["number_open_complaints"].value_counts()

number_open_complaints
0.0    830
1.0    138
2.0     50
3.0     34
4.0     13
5.0      6
Name: count, dtype: int64

In [95]:
insurance_df["number_open_complaints"] = insurance_df["number_open_complaints"].astype("Int64")

In [96]:
insurance_df["number_open_complaints"].value_counts()

number_open_complaints
0    830
1    138
2     50
3     34
4     13
5      6
Name: count, dtype: Int64

## Exercise 4: Dealing with Null values

Identify any columns with null or missing values. Identify how many null values each column has. You can use the `isnull()` function in pandas to find columns with null values.

Decide on a strategy for handling the null values. There are several options, including:

- Drop the rows or columns with null values
- Fill the null values with a specific value (such as the column mean or median for numerical variables, and mode for categorical variables)
- Fill the null values with the previous or next value in the column
- Fill the null values based on a more complex algorithm or model (note: we haven't covered this yet)

Implement your chosen strategy to handle the null values. You can use the `fillna()` function in pandas to fill null values or `dropna()` function to drop null values.

Verify that your strategy has successfully handled the null values. You can use the `isnull()` function again to check if there are still null values in the dataset.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling null values.

After formatting data types, as a last step, convert all the numeric variables to integers.

In [98]:
# Your code here
#Checking null values in columns
insurance_df.isnull().any()

id_customer               True
state                     True
gender                    True
education                 True
c_lifetime_value          True
Income                    True
monthly_premium_auto      True
number_open_complaints    True
policy_type               True
vehicle_class             True
total_claim_amount        True
dtype: bool

In [99]:
insurance_df.isnull().sum()

id_customer               2937
state                     2937
gender                    3054
education                 2937
c_lifetime_value          2940
Income                    2937
monthly_premium_auto      2937
number_open_complaints    2937
policy_type               2937
vehicle_class             2937
total_claim_amount        2937
dtype: int64

In [100]:
insurance_df.isna().sum(axis=1)

0        2
1        0
2        0
3        0
4        0
        ..
4003    11
4004    11
4005    11
4006    11
4007    11
Length: 4008, dtype: int64

In [101]:
# Dropping columns with  Null Values
insurance_df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[4008 rows x 0 columns]

In [103]:
#Setting a minimum the values for a row to be kept
insurance_df.dropna(thresh=3).tail()

,id_customer,state,gender,education,c_lifetime_value,Income,monthly_premium_auto,number_open_complaints,policy_type,vehicle_class,total_claim_amount
1066,TM65736,Oregon,M,Master,305955.03%,38644.0,78.0,1,Personal Auto,Four-Door Car,361.455219
1067,VJ51327,Cali,F,High School or Below,2031499.76%,63209.0,102.0,2,Personal Auto,SUV,207.320041
1068,GS98873,Arizona,F,Bachelor,323912.47%,16061.0,88.0,0,Personal Auto,Four-Door Car,633.600000
1069,CW49887,California,F,Master,462680.11%,79487.0,114.0,0,Special Auto,SUV,547.200000
1070,MY31220,California,F,College,899704.02%,54230.0,112.0,0,Personal Auto,Two-Door Car,537.600000

In [104]:
insurance_df.isnull().sum()

id_customer               2937
state                     2937
gender                    3054
education                 2937
c_lifetime_value          2940
Income                    2937
monthly_premium_auto      2937
number_open_complaints    2937
policy_type               2937
vehicle_class             2937
total_claim_amount        2937
dtype: int64

In [105]:
insurance_df.isna().sum(axis=1).value_counts()

11    2937
0      952
1      118
2        1
Name: count, dtype: int64

In [106]:
#Checking the number of calls
insurance_df.shape[1]

11

In [107]:
#Dropping rows where all values are Null
insurance_df = insurance_df.dropna(how="all")

In [108]:
insurance_df.shape

(1071, 11)

In [109]:
insurance_df.isna().sum(axis=1).value_counts()

0    952
1    118
2      1
Name: count, dtype: int64

In [110]:
#Checking columns with missing information on what was left
insurance_df[insurance_df.isna().any(axis=1)].isna().sum()

id_customer                 0
state                       0
gender                    117
education                   0
c_lifetime_value            3
Income                      0
monthly_premium_auto        0
number_open_complaints      0
policy_type                 0
vehicle_class               0
total_claim_amount          0
dtype: int64

In [115]:
#Filling missing values in the gender column with the mode
insurance_df["gender"] = insurance_df["gender"].fillna(insurance_df["gender"].mode()[0])

In [117]:
#Dropping rows with null alues in c_lifetime_value
insurance_df["c_lifetime_value"].isnull().sum()

np.int64(3)

In [118]:
insurance_df["c_lifetime_value"].shape

(1071,)

## Exercise 5: Dealing with duplicates

Use the `.duplicated()` method to identify any duplicate rows in the dataframe.

Decide on a strategy for handling the duplicates. Options include:
- Dropping all duplicate rows
- Keeping only the first occurrence of each duplicated row
- Keeping only the last occurrence of each duplicated row
- Dropping duplicates based on a subset of columns
- Dropping duplicates based on a specific column

Implement your chosen strategy using the `drop_duplicates()` function.

Verify that your strategy has successfully handled the duplicates by checking for duplicates again using `.duplicated()`.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling duplicates.

Save the cleaned dataset to a new CSV file.

*Hint*: *after dropping duplicates, reset the index to ensure consistency*.

In [119]:
# Identifying duplicates
insurance_df.duplicated().sum()

np.int64(0)

In [ ]:
#No duplicates found

In [120]:
insurance_df = insurance_df.reset_index(drop=True)

In [121]:
insurance_df.index

RangeIndex(start=0, stop=1071, step=1)

# Bonus: Challenge 2: creating functions on a separate `py` file

Put all the data cleaning and formatting steps into functions, and create a main function that performs all the cleaning and formatting.

Write these functions in separate .py file(s). By putting these steps into functions, we can make the code more modular and easier to maintain.

*Hint: autoreload module is a utility module in Python that allows you to automatically reload modules in the current session when changes are made to the source code. This can be useful in situations where you are actively developing code and want to see the effects of changes you make without having to constantly restart the Python interpreter or Jupyter Notebook kernel.*

In [ ]:
# Your code here

# Bonus: Challenge 3: Analyzing Clean and Formated Data

You have been tasked with analyzing the data to identify potential areas for improving customer retention and profitability. Your goal is to identify customers with a high policy claim amount and a low customer lifetime value.

In the Pandas Lab, we only looked at high policy claim amounts because we couldn't look into low customer lifetime values. If we had tried to work with that column, we wouldn't have been able to because customer lifetime value wasn't clean and in its proper format. So after cleaning and formatting the data, let's get some more interesting insights!

Instructions:

- Review the statistics again for total claim amount and customer lifetime value to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount and a low customer lifetime value. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount, and clients with a low customer lifetime value to be those in the bottom 25% of the customer lifetime value. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile and a customer lifetime value in the bottom 25th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount and low customer lifetime value data. To do so, select both columns of the dataframe simultaneously and pass it to the `.describe()` method. This will give you descriptive statistics, such as mean, median, standard deviation, minimum and maximum values for both columns at the same time, allowing you to compare and analyze their characteristics.

In [ ]:
# Your code here